/**
 * Copyright (c) 2026 Kunji Finance.
 * All rights reserved.
 * This code is proprietary and confidential.
 */

import type { Budget, SavingsGoal, Transaction, Investment } from '@prisma/client';

/**
 * An insight generated by the rule-based engine.
 */
export interface GeneratedInsight {
    title: string;
    content: string;
    type: 'spending' | 'saving' | 'investing' | 'general';
}

/**
 * Generates AI-powered, rule-based financial insights for a user.
 *
 * @param transactions - The user's recent transactions.
 * @param budgets - The user's current budgets.
 * @param savingsGoals - The user's savings goals.
 * @param investments - The user's investment holdings.
 * @returns Array of generated insights.
 */
export function generateInsights(
    transactions: Transaction[],
    budgets: Budget[],
    savingsGoals: SavingsGoal[],
    investments: Investment[]
): GeneratedInsight[] {
    const insights: GeneratedInsight[] = [];
    const now = new Date();
    const startOfMonth = new Date(now.getFullYear(), now.getMonth(), 1);
    const daysInMonth = new Date(now.getFullYear(), now.getMonth() + 1, 0).getDate();
    const dayOfMonth = now.getDate();
    const monthFraction = dayOfMonth / daysInMonth;

    // ── 1.  Budget overspend alerts ────────────────────────────────────────
    for (const budget of budgets) {
        const spent = transactions
            .filter(
                (t) =>
                    t.category === budget.category &&
                    t.type === 'expense' &&
                    new Date(t.date) >= startOfMonth
            )
            .reduce((sum, t) => sum + t.amount, 0);

        const pct = (spent / budget.amount) * 100;

        if (pct >= 100) {
            insights.push({
                title: `${budget.category} budget exceeded`,
                content: `You have spent ₹${spent.toLocaleString('en-IN')} against a ₹${budget.amount.toLocaleString('en-IN')} budget for ${budget.category}. Consider cutting back for the rest of the month.`,
                type: 'spending',
            });
        } else if (pct >= budget.alertThreshold) {
            const remaining = budget.amount - spent;
            insights.push({
                title: `${budget.category} budget running low`,
                content: `You've used ${Math.round(pct)}% of your ${budget.category} budget with ${daysInMonth - dayOfMonth} days remaining. Only ₹${remaining.toLocaleString('en-IN')} left.`,
                type: 'spending',
            });
        }
    }

    // ── 2. Savings goal on-track / behind ─────────────────────────────────
    for (const goal of savingsGoals) {
        const targetDate = new Date(goal.targetDate);
        if (targetDate <= now) continue;

        const totalDays =
            (targetDate.getTime() - new Date(goal.createdAt ?? now).getTime()) /
            (1000 * 60 * 60 * 24);
        const elapsedDays = (now.getTime() - new Date(goal.createdAt ?? now).getTime()) /
            (1000 * 60 * 60 * 24);
        const expectedProgress = totalDays > 0 ? elapsedDays / totalDays : 0;
        const actualProgress = goal.targetAmount > 0
            ? goal.currentAmount / goal.targetAmount
            : 0;

        if (actualProgress >= 0.95) {
            insights.push({
                title: `Almost reached "${goal.name}"!`,
                content: `You're at ${Math.round(actualProgress * 100)}% of your ₹${goal.targetAmount.toLocaleString('en-IN')} goal for ${goal.name}. Just ₹${(goal.targetAmount - goal.currentAmount).toLocaleString('en-IN')} more to go!`,
                type: 'saving',
            });
        } else if (actualProgress < expectedProgress - 0.1) {
            insights.push({
                title: `"${goal.name}" goal is behind schedule`,
                content: `You're at ${Math.round(actualProgress * 100)}% but should be at ${Math.round(expectedProgress * 100)}% by now. Consider increasing your monthly contribution.`,
                type: 'saving',
            });
        }
    }

    // ── 3. Monthly income vs expenses savings rate ─────────────────────────
    const monthlyIncome = transactions
        .filter((t) => t.type === 'income' && new Date(t.date) >= startOfMonth)
        .reduce((sum, t) => sum + t.amount, 0);
    const monthlyExpenses = transactions
        .filter((t) => t.type === 'expense' && new Date(t.date) >= startOfMonth)
        .reduce((sum, t) => sum + t.amount, 0);

    if (monthlyIncome > 0) {
        const savingsRate = ((monthlyIncome - monthlyExpenses) / monthlyIncome) * 100;
        if (savingsRate >= 30) {
            insights.push({
                title: 'Excellent savings rate this month!',
                content: `You're saving ${Math.round(savingsRate)}% of your income this month. That's above the recommended 20%. Keep it up!`,
                type: 'saving',
            });
        } else if (savingsRate < 10 && monthFraction > 0.5) {
            insights.push({
                title: 'Low savings rate this month',
                content: `You're saving only ${Math.round(savingsRate)}% of your income. Try to reduce spending in your top expense categories to hit the 20% target.`,
                type: 'saving',
            });
        }
    }

    // ── 4. Unusual spending in a category ─────────────────────────────────
    const categorySpend: Record<string, number[]> = {};
    for (const t of transactions) {
        if (t.type !== 'expense') continue;
        if (!categorySpend[t.category]) categorySpend[t.category] = [];
        categorySpend[t.category].push(t.amount);
    }

    for (const [category, amounts] of Object.entries(categorySpend)) {
        if (amounts.length < 3) continue;
        const avg = amounts.slice(0, -1).reduce((a, b) => a + b, 0) / (amounts.length - 1);
        const latest = amounts[amounts.length - 1];
        if (latest > avg * 2 && latest > 1000) {
            insights.push({
                title: `Unusual spend in ${category}`,
                content: `Your latest ${category} transaction of ₹${latest.toLocaleString('en-IN')} is over 2× your average of ₹${Math.round(avg).toLocaleString('en-IN')}. Was this expected?`,
                type: 'spending',
            });
        }
    }

    // ── 5. Portfolio allocation check ─────────────────────────────────────
    if (investments.length > 0) {
        const total = investments.reduce((sum, i) => sum + i.currentValue, 0);
        const equityTypes = ['stocks', 'mutual-fund', 'etf'];
        const equityValue = investments
            .filter((i) => equityTypes.includes(i.type))
            .reduce((sum, i) => sum + i.currentValue, 0);
        const equityPct = (equityValue / total) * 100;

        if (equityPct > 80) {
            insights.push({
                title: 'Portfolio is heavily in equity',
                content: `${Math.round(equityPct)}% of your portfolio is in equities. Consider adding bonds or fixed deposits for better risk management.`,
                type: 'investing',
            });
        } else if (equityPct < 30) {
            insights.push({
                title: 'Consider more equity exposure',
                content: `Only ${Math.round(equityPct)}% of your portfolio is in equities. For long-term growth, financial advisors recommend at least 50–60% equity allocation.`,
                type: 'investing',
            });
        }
    }

    return insights.slice(0, 5); // Return max 5 insights
}
